### ISSUE TITLE
be more clear about what happens to dependant associations

### ISSUE THREAD

**Issue by osheroff** [grosser/soft_deletion#15]
in the README, you say:

```
# soft delete them including all dependencies that are marked as :destroy, :delete_all, :nullify
```

But it seems we actually only soft-delete associations that also support soft_delete:
https://github.com/grosser/soft_deletion/blob/master/lib/soft_deletion/core.rb#L23

That's a fine strategy but we should say so if that's the intention...

**Comment by grosser** [comment]
sounds good, updated the readem
