### ISSUE TITLE
with_deleted not working with subclasses

### ISSUE THREAD

**Issue by joelmichael** [grosser/soft_deletion#26]
I think I found a real problem this time. Just to be sure, here's a spec as a git patch.

[patch.txt](https://github.com/grosser/soft_deletion/files/423877/patch.txt)

**Comment by grosser** [comment]
that looks about right ... can you make a PR ?

change could be that we look at the tablename instead of the class name ...
or the name of the first non-abstract ancestor ?

**Comment by joelmichael** [comment]
Actually, it looks like there is a PR for this issue already made a few weeks ago.

**Comment by grosser** [comment]
this PR https://github.com/grosser/soft_deletion/pull/23 shows that something is broken on rails 5 

is that what you are having trouble with or is it a general issue ?

**Comment by grosser** [comment]
think I found a simple workaround ...

**Comment by joelmichael** [comment]
We're on 4.2.7.1 and it still happens

**Comment by grosser** [comment]
can you try https://github.com/grosser/soft_deletion/pull/23

**Comment by grosser** [comment]
or did you already try that ?

the previous issue was resolved by some internal app-specific changes

https://github.com/grosser/soft_deletion/issues/24

**Comment by joelmichael** [comment]
I've tried it now and the tests all pass for me

**Comment by joelmichael** [comment]
I can confirm that this PR fixes the bug in my code.

**Comment by grosser** [comment]
0.8.1

**Comment by joelmichael** [comment]
Thanks for fixing this, btw, we are using this at Hired... Nate Clark says hi.
