### ISSUE TITLE
Request: Keep a change log

### ISSUE THREAD

**Issue by xtagon** [grosser/soft_deletion#35]
Hi,

First of all, thank you for writing this library 👍 

Would you consider keeping a simple change log between releases? I tend to check change logs before updating libraries my apps depends on, but I don't see one for this library. It's much easier to check a change log to see what's backwards incompatibile and what's fixed than to dive into commit logs.

Thanks!

**Comment by grosser** [comment]
I'm too lazy for that ... maybe if there was some good automation in `bump` for that ...

**Comment by xtagon** [comment]
There are tools like https://github.com/skywinder/github-changelog-generator if you're into that

**Comment by grosser** [comment]
I guess ideally it would be some external web-service that we just link to
:D
changelog-as-a-service ... that parses special PR annotations or so ...
could be a fun project :)

**Comment by xtagon** [comment]
I personally prefer that changelogs are kept separate from PRs and commit messsages, so attention can be on what has changed at a high level. See http://keepachangelog.com/en/1.0.0/

However, this is your repo - it's only a suggestion :-)

Luckily most releases in this gem are small enough I can just read through the commits
