### ISSUE TITLE
Rails 7

### ISSUE THREAD

**Issue by apauly** [grosser/soft_deletion#46]
Hey there,

I tried updating an existing application to Rails 7, and the version for this gem dropped from `1.6.0` to `0.5.6` - I guess because that was the latest version that didn't have any active record dependencies declared in the gemspec.

Is this gem still maintained and are there any plans to support Rails/ActiveRecord 7?

**Comment by grosser** [comment]
it's maintained but we don't use rails 7 yet, PR welcome

**Comment by apauly** [comment]
Alright, thanks for the quick response. I will consider creating a PR during the next weeks then ✌️
